config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'


  post '/send_mail', to: 'pages#send_mail'
  get "servicos", to: "pages#servicos"

  get "institucional", to: "pages#institucional"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def send_mail
    @contact_name = params[:nome]
    @email = params[:email]
    @body = params[:comentarios]
    ContactMailer.contact_mail(@contact_name, @email, @body).deliver
    redirect_to root_url, notice: 'Mensagem enviada.'
  end
  def servicos
  end

  def institucional
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>Rodrigo Fernandes</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
<form action="https://formspree.io/your@email.com"
      method="POST">
    <input type="text" name="name">
    <input type="email" name="_replyto">
    <input type="submit" value="Send">
</form>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('http://res.cloudinary.com/rodrigofernandes/image/upload/v1506026557/black-and-white-architecture-skyline-street-building-city-1053294-pxhere.com_my1nhc.jpg');">
  <div class="banner-content">
    <h1>Rodrigo F. Assalve Advogados</h1>
    <hr>
    <p> OAB/SP 361482 </p>
  </div>
</div>

app/views/pages/institucional.html.erb
<div class="banner" style="background-image: url('http://res.cloudinary.com/rodrigofernandes/image/upload/e_grayscale/v1506112472/pedestrian-road-skyline-street-highway-city-831040-pxhere.com_dm7wcj.jpg ');">
  <div class="institucional-description hidden-xs hidden-md hidden-sm">
    <h3>Sobre o escritório</h3>
    <p align="justify" style="color: black;">
    <strong><i><u>Rodrigo Fernandes Assalve Advogados</u></i></strong> é um escritório de advocacia atuante nos ramos do Direito Civil, Direito do Consumidor, Direito Empresarial e Empresarial Trabalhista.</p>
    <br>
    <p align="justify" style="color: black;">O escritório pratica a advocacia com visão de negócios e foco em resultados, desenvolvendo soluções customizadas para seus clientes que operam em diversos setores da economia.</p>
    <br>
    <p align="justify" style="color: black;">Tendo como objetivo principal a segurança e qualidade na prestação dos serviços, para alcançar a máxima eficiência na operação de seus clientes. Em busca da conquista do grau máximo de desempenho dos serviços demandados, as questões confiadas ao escritório são sempre tratadas e desenvolvidas de forma individual e com extremo zelo.</p>
    <br>
    <p align="justify" style="color: black;">Estes elementos formam a cultura organizacional que alia <u>pioneirismo, tradição e inovação.</u></p>
  </div>
  <div class="mini-institucional-description hidden-lg">
    <h3>Sobre o escritório</h3>
    <p align="justify" style="color: black;">
    <strong><i><u>Rodrigo Fernandes Assalve Advogados</u></i></strong> é um escritório de advocacia atuante nos ramos do Direito Civil, Direito do Consumidor, Direito Empresarial e Empresarial Trabalhista.</p>
    <br>
    <p align="justify" style="color: black;">O escritório pratica a advocacia com visão de negócios e foco em resultados, desenvolvendo soluções customizadas para seus clientes que operam em diversos setores da economia.</p>
    <br>
    <p align="justify" style="color: black;">Tendo como objetivo principal a segurança e qualidade na prestação dos serviços, para alcançar a máxima eficiência na operação de seus clientes. Em busca da conquista do grau máximo de desempenho dos serviços demandados, as questões confiadas ao escritório são sempre tratadas e desenvolvidas de forma individual e com extremo zelo.</p>
    <br>
    <p align="justify" style="color: black;">Estes elementos formam a cultura organizacional que alia <u>pioneirismo, tradição e inovação.</u></p>
  </div>
</div>

app/views/pages/servicos.html.erb
  <div class="works-banner">
    <h1>Áreas de atuação</h1>
    <div class="hidden-xs hidden-sm hidden-sm">
      <p>Clique abaixo e conheça em detalhe todos os serviços do escritório</p>
    </div>
    <div class="large-cards hidden-xs hidden-sm hidden-md">
      <figure class="card-work" data-toggle="modal" data-target=".comercial">
        <%= cl_image_tag("growth-money-business-close-up-cash-currency-572367-pxhere.com_yzu3jq.jpg") %>
        <figcaption>
          <h3>Comercial</h3>
        </figcaption>
      </figure>

      <figure class="card-work" data-toggle="modal" data-target=".societario">
        <%= cl_image_tag("hand-man-suit-photography-finger-giving-1187331-pxhere.com_isw399.jpg") %>
        <figcaption>
          <h3>Societário</h3>
        </figcaption>
      </figure>

      <figure class="card-work" data-toggle="modal" data-target=".consumidor">
      <%= cl_image_tag("sky-monument-statue-contrast-blue-scale-897175-pxhere.com_iaqsra.jpg") %>
        <figcaption>
          <h3>Consumidor</h3>
        </figcaption>
      </figure>

      <figure class="card-work" data-toggle="modal" data-target=".contratos">
      <%= cl_image_tag("writing-hand-pattern-paper-brand-art-603024-pxhere.com_sccl3v.jpg")
     %>
        <figcaption>
          <h3>Contratos</h3>
        </figcaption>
      </figure>

      <figure class="card-work" data-toggle="modal" data-target=".trabalhista">
      <%= cl_image_tag("carteira_madawf.jpg") %>
        <figcaption>
          <h3>Trabalhista</h3>
        </figcaption>
      </figure>
    </div>

    <div class="hidden-lg">
      <ul class="work-menu">
        <a data-toggle="modal" data-target=".comercial">
          <li class="work-menu-link">
            Comercial
          </li>
        </a>
        <a data-toggle="modal" data-target=".societario">
          <li class="work-menu-link">
            Societário
          </li>
        </a>
        <a data-toggle="modal" data-target=".consumidor">
          <li class="work-menu-link">
            Consumidor
          </li>
        </a>
        <a data-toggle="modal" data-target=".contratos">
          <li class="work-menu-link">
            Contratos
          </li>
        </a>
        </li>
        <a data-toggle="modal" data-target=".trabalhista">
          <li class="work-menu-link">
            Trabalhista
          </li>
        </a>
      </ul>
    </div>
  </div>
<%= render "shared/modal" %>

app/views/pages/work.html.erb
  <div class="works-banner">
    <h1>Áreas de atuação</h1>
    <figure class="card-work" data-toggle="modal" data-target=".comercial">
      <%= cl_image_tag("growth-money-business-close-up-cash-currency-572367-pxhere.com_yzu3jq.jpg") %>
      <figcaption>
        <h3>Comercial</h3>
      </figcaption>
    </figure>

    <figure class="card-work" data-toggle="modal" data-target=".societario">
      <%= cl_image_tag("hand-man-suit-photography-finger-giving-1187331-pxhere.com_isw399.jpg") %>
      <figcaption>
        <h3>Societário</h3>
      </figcaption>
    </figure>

    <figure class="card-work" data-toggle="modal" data-target=".consumidor">
    <%= cl_image_tag("sky-monument-statue-contrast-blue-scale-897175-pxhere.com_iaqsra.jpg") %>
      <figcaption>
        <h3>Consumidor</h3>
      </figcaption>
    </figure>

    <figure class="card-work" data-toggle="modal" data-target=".contratos">
    <%= cl_image_tag("writing-hand-pattern-paper-brand-art-603024-pxhere.com_sccl3v.jpg")
   %>
      <figcaption>
        <h3>Contratos</h3>
      </figcaption>
    </figure>

    <figure class="card-work" data-toggle="modal" data-target=".trabalhista">
    <%= cl_image_tag("carteira_madawf.jpg") %>
      <figcaption>
        <h3>Trabalhista</h3>
      </figcaption>
    </figure>
  </div>

<%= render "shared/modal" %>

app/views/shared/_email.html.erb
<div class="modal fade" id="email" tabindex="-1" role="dialog" aria-labelledby="comercial" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="comercial"><strong>Contato</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <%= form_tag(send_mail_path) do %>
          <div class="form-group">
            <%= label_tag 'nome', 'Nome' %>
            <%= text_field_tag 'nome', nil, class: 'form-control', placeholder: 'Seu nome' %>
          </div>
          <div class="form-group">
              <%= label_tag 'email', 'Email' %>
              <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Seu e-mail' %>
          </div>
          <div class="form-group">
              <%= label_tag 'comentarios', 'Comentários' %>
              <%= text_area_tag 'comentarios', nil, class: 'form-control', rows: 4, placeholder: 'Comentários...' %>
          </div>
          <%= submit_tag 'Enviar', class: 'btn btn-default btn-about pull-right' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="global-footer">
  <div class="container footer-information hidden-sm hidden-xs">
    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <p><i class="fa fa-phone" aria-hidden="true"></i> (11) 4116-6256 </p>
      </div>
      <div class="col-xs-6 col-sm-4">
        <a data-toggle="modal" data-target="#email" id="contact">
          Entre em contato!
        </a>
      </div>
      <div class="col-xs-12 col-sm-4">
        <p><i class="fa fa-envelope-o" aria-hidden="true"></i> rodrigo.assalve@adv.oabsp.org.br</p>
      </div>
    </div>
  </div>
  <div class="container footer-information hidden-md hidden-lg">
    <div class="row">
      <a data-toggle="modal" data-target="#email" id="contact">
        Entre em contato!
      </a>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <p><i class="fa fa-phone" aria-hidden="true"></i> (11) 4116-6256 </p>
      </div>
      <div class="col-xs-12 col-sm-6">
        <p><i class="fa fa-envelope-o" aria-hidden="true"></i> rodrigo.assalve@adv.oabsp.org.br</p>
      </div>
    </div>
  </div>
  <div class="assignature">
    <p><i>Desenvolvido por Luana Perin e Bruno Cerqueira</i></p>
  </div>
</div>

<%= render "shared/email" %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade comercial" tabindex="-1" role="dialog" aria-labelledby="comercial" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="comercial"><strong>Comercial</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <p align="justify">Os clientes recebem assessoria na condução de suas relações e práticas comerciais, referentes à compra e venda mercantil, títulos de créditos, protestos e representação comercial.<br></p>
        <p align="justify">Caso o cliente tenha dificuldade em recebimento de ativos o escritório trabalha com a recuperação de créditos de forma extrajudicial, além de cobranças judiciais por meio das ações de execução, monitória, habilitações de créditos em recuperação de empresas e falências.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade societario" tabindex="-1" role="dialog" aria-labelledby="societario" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="societario"><strong>Societário</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <p align="justify">O escritório oferece planejamento societário a companhias nacionais e estrangeiras, bem como assessoria na constituição de sociedades e filiais, associações e fundações, e, também, atuando em dissoluções, incorporações, cisões, fusões e transformações.</p>

        <p align="justify">O auxílio aos clientes está ligado a estruturação e tomadas de decisões nas operações de fusão, aquisição e cisão de empresas, inclusive para companhias estrangeiras que desejem ingressar no mercado brasileiro, para tanto, realizamos a auditoria legal (due diligence) e negociações, além de confeccionarmos os instrumentos societários necessários.</p>

        <p align="justify">Os serviços de constituição de empresas, obtenção de CNPJ e inscrições municipais e estudais também são prestados pelo escritório.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade consumidor" tabindex="-1" role="dialog" aria-labelledby="consumidor" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="consumidor"><strong>Consumidor</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <p align="justify">O serviço prestado nesse ramo do direito está ligado a realização de defesas nas esferas judiciais e administrativas, especialmente perante PROCON, Juizados Especiais Cíveis e Justiça Comum, além de proceder negociações junto aos consumidores, sempre visando reduzir o custo total do cliente.</p>

        <p align="justify">O escritório, ainda, faz análises de procedimentos para verificar se os adotados pela empresa, encontram-se conforme os ditames do Código de Defesa do Consumidor e assim eliminar ou mitigar riscos frente a relações não saudáveis à empresa.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade contratos" tabindex="-1" role="dialog" aria-labelledby="contratos" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="contratos"><strong>Contratos</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <p align="justify">O escritório assessora empresas na confecção e análise de instrumentos contratuais, sejam eles comerciais ou cíveis, e, também, assessora em negociações dos termos, bem como confecciona pareceres para fundamentar as pretensões de seus clientes.</p>

        <p align="justify">Nas diversas atividades desenvolvidas nesta área, ressalta-se a análise e elaboração dos contratos de compra e venda; arrendamento; locação de bens, podendo ser móveis ou imóveis, sendo que, os imóveis podem ser residenciais ou comerciais, inclusive Shopping Center, contratos de concessão comercial e contratos de franquia e licenciamento.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade trabalhista" tabindex="-1" role="dialog" aria-labelledby="trabalhista" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-xs-10">
            <h5 class="modal-title" id="trabalhista"><strong>Trabalhista</strong></h5>
          </div>
          <div class="col-xs-2">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <p align="justify">Os serviços abrangem a defesa e o acompanhamento de reclamações trabalhistas, atuando de forma específica a cada tipo de cliente, desde a fase inicial até as últimas instâncias do Judiciário.</p>

        <p align="justify">No âmbito consultivo o escritório visa sempre obter os melhores resultados presente à complexa e delicada legislação trabalhista, tendo como os serviços abrangentes reuniões, consultas, orientações para discutir políticas ou interpretações jurídicas.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="total-page hidden-xs hidden-sm hidden-md">
  <nav class="navbar-basic navbar-main-hidden hidden-menu">

    <!-- Right Navigation -->
    <ul class="navbar-right">
      <li href="" class="navbar-item navbar-link">
        <%= link_to root_path do %>
        <i class="fa fa-home" aria-hidden="true"></i>
        <span class="icon-name">Página inicial</span>
        <% end %>
      </li>
      <li href="" class="navbar-item navbar-link">
        <%= link_to servicos_path do %>
        <i class="fa fa-gavel" aria-hidden="true"></i>
        <span class="icon-name">Serviços</span>
        <% end %>
      </li>
      <li href="" class="navbar-item navbar-link">
        <%= link_to institucional_path do %>
        <i class="fa fa-university" aria-hidden="true"></i>
        <span class="icon-name">Sobre</span>
        <% end %>
      </li>
      <li href="" class="navbar-item navbar-link">
        <%= link_to "#", data: {toggle: "modal", target: "#email"} do %>
          <i class="fa fa-envelope-o" aria-hidden="true"></i>
          <span class="icon-name">Contato</span>
        <% end %>
      </li>
    </ul>
  </nav>


</div>

    <!-- Dropdown appearing on mobile only -->

<nav class="cel-menu hidden-lg">
    <a id="burger">
      <i class="fa fa-caret-square-o-down fa-2x" aria-hidden="true"></i>
    </a>

    <ul id="submenu">
      <li>
        <%= link_to root_path do %>
          <span class="icon-name">Página inicial</span>
        <% end %>
      </li>
      <li>
        <%= link_to servicos_path do %>
          <span class="icon-name">Serviços</span>
        <% end %>
      </li>
      <li>
        <%= link_to institucional_path do %>
          <span class="icon-name">Sobre</span>
        <% end %>
      </li>
      <li>
        <%= link_to "#", data: {toggle: "modal", target: "#email"} do %>
          <span class="icon-name">Contato</span>
        <% end %>
      </li>
    </ul>
  </nav>